#!/usr/bin/env bash
java -jar macrophage.jar true 0 results/ph_effect/ 0_ph_effect.csv -1 125 
java -jar macrophage.jar true 1 results/ph_effect/ 1_ph_effect.csv -1 125 
java -jar macrophage.jar true 2 results/ph_effect/ 2_ph_effect.csv -1 125 
java -jar macrophage.jar true 3 results/ph_effect/ 3_ph_effect.csv -1 125 
java -jar macrophage.jar true 4 results/ph_effect/ 4_ph_effect.csv -1 125 
java -jar macrophage.jar true 5 results/ph_effect/ 5_ph_effect.csv -1 125 
java -jar macrophage.jar true 6 results/ph_effect/ 6_ph_effect.csv -1 125 
java -jar macrophage.jar true 7 results/ph_effect/ 7_ph_effect.csv -1 125 
java -jar macrophage.jar true 8 results/ph_effect/ 8_ph_effect.csv -1 125 
java -jar macrophage.jar true 9 results/ph_effect/ 9_ph_effect.csv -1 125 
java -jar macrophage.jar true 10 results/ph_effect/ 10_ph_effect.csv -1 125 
java -jar macrophage.jar true 11 results/ph_effect/ 11_ph_effect.csv -1 125 
java -jar macrophage.jar true 12 results/ph_effect/ 12_ph_effect.csv -1 125 
java -jar macrophage.jar true 13 results/ph_effect/ 13_ph_effect.csv -1 125 
java -jar macrophage.jar true 14 results/ph_effect/ 14_ph_effect.csv -1 125 
java -jar macrophage.jar true 15 results/ph_effect/ 15_ph_effect.csv -1 125 
java -jar macrophage.jar true 16 results/ph_effect/ 16_ph_effect.csv -1 125 
java -jar macrophage.jar true 17 results/ph_effect/ 17_ph_effect.csv -1 125 
java -jar macrophage.jar true 18 results/ph_effect/ 18_ph_effect.csv -1 125 
java -jar macrophage.jar true 19 results/ph_effect/ 19_ph_effect.csv -1 125 
java -jar macrophage.jar true 20 results/ph_effect/ 20_ph_effect.csv -1 125 
java -jar macrophage.jar true 21 results/ph_effect/ 21_ph_effect.csv -1 125 
java -jar macrophage.jar true 22 results/ph_effect/ 22_ph_effect.csv -1 125 
java -jar macrophage.jar true 23 results/ph_effect/ 23_ph_effect.csv -1 125 
java -jar macrophage.jar true 24 results/ph_effect/ 24_ph_effect.csv -1 125 
java -jar macrophage.jar true 25 results/ph_effect/ 25_ph_effect.csv -1 125 
java -jar macrophage.jar true 26 results/ph_effect/ 26_ph_effect.csv -1 125 
java -jar macrophage.jar true 27 results/ph_effect/ 27_ph_effect.csv -1 125 
java -jar macrophage.jar true 28 results/ph_effect/ 28_ph_effect.csv -1 125 
java -jar macrophage.jar true 29 results/ph_effect/ 29_ph_effect.csv -1 125 
java -jar macrophage.jar true 30 results/ph_effect/ 30_ph_effect.csv -1 125 
java -jar macrophage.jar true 31 results/ph_effect/ 31_ph_effect.csv -1 125 
java -jar macrophage.jar true 32 results/ph_effect/ 32_ph_effect.csv -1 125 
java -jar macrophage.jar true 33 results/ph_effect/ 33_ph_effect.csv -1 125 
java -jar macrophage.jar true 34 results/ph_effect/ 34_ph_effect.csv -1 125 
java -jar macrophage.jar true 35 results/ph_effect/ 35_ph_effect.csv -1 125 
java -jar macrophage.jar true 36 results/ph_effect/ 36_ph_effect.csv -1 125 
java -jar macrophage.jar true 37 results/ph_effect/ 37_ph_effect.csv -1 125 
java -jar macrophage.jar true 38 results/ph_effect/ 38_ph_effect.csv -1 125 
java -jar macrophage.jar true 39 results/ph_effect/ 39_ph_effect.csv -1 125 
java -jar macrophage.jar true 40 results/ph_effect/ 40_ph_effect.csv -1 125 
java -jar macrophage.jar true 41 results/ph_effect/ 41_ph_effect.csv -1 125 
java -jar macrophage.jar true 42 results/ph_effect/ 42_ph_effect.csv -1 125 
java -jar macrophage.jar true 43 results/ph_effect/ 43_ph_effect.csv -1 125 
java -jar macrophage.jar true 44 results/ph_effect/ 44_ph_effect.csv -1 125 
java -jar macrophage.jar true 45 results/ph_effect/ 45_ph_effect.csv -1 125 
java -jar macrophage.jar true 46 results/ph_effect/ 46_ph_effect.csv -1 125 
java -jar macrophage.jar true 47 results/ph_effect/ 47_ph_effect.csv -1 125 
java -jar macrophage.jar true 48 results/ph_effect/ 48_ph_effect.csv -1 125 
java -jar macrophage.jar true 49 results/ph_effect/ 49_ph_effect.csv -1 125 
java -jar macrophage.jar true 50 results/ph_effect/ 50_ph_effect.csv -1 125 
java -jar macrophage.jar true 51 results/ph_effect/ 51_ph_effect.csv -1 125 
java -jar macrophage.jar true 52 results/ph_effect/ 52_ph_effect.csv -1 125 
java -jar macrophage.jar true 53 results/ph_effect/ 53_ph_effect.csv -1 125 
java -jar macrophage.jar true 54 results/ph_effect/ 54_ph_effect.csv -1 125 
java -jar macrophage.jar true 55 results/ph_effect/ 55_ph_effect.csv -1 125 
java -jar macrophage.jar true 56 results/ph_effect/ 56_ph_effect.csv -1 125 
java -jar macrophage.jar true 57 results/ph_effect/ 57_ph_effect.csv -1 125 
java -jar macrophage.jar true 58 results/ph_effect/ 58_ph_effect.csv -1 125 
java -jar macrophage.jar true 59 results/ph_effect/ 59_ph_effect.csv -1 125 
java -jar macrophage.jar true 60 results/ph_effect/ 60_ph_effect.csv -1 125 
java -jar macrophage.jar true 61 results/ph_effect/ 61_ph_effect.csv -1 125 
java -jar macrophage.jar true 62 results/ph_effect/ 62_ph_effect.csv -1 125 
java -jar macrophage.jar true 63 results/ph_effect/ 63_ph_effect.csv -1 125 
java -jar macrophage.jar true 64 results/ph_effect/ 64_ph_effect.csv -1 125 
java -jar macrophage.jar true 65 results/ph_effect/ 65_ph_effect.csv -1 125 
java -jar macrophage.jar true 66 results/ph_effect/ 66_ph_effect.csv -1 125 
java -jar macrophage.jar true 67 results/ph_effect/ 67_ph_effect.csv -1 125 
java -jar macrophage.jar true 68 results/ph_effect/ 68_ph_effect.csv -1 125 
java -jar macrophage.jar true 69 results/ph_effect/ 69_ph_effect.csv -1 125 
java -jar macrophage.jar true 70 results/ph_effect/ 70_ph_effect.csv -1 125 
java -jar macrophage.jar true 71 results/ph_effect/ 71_ph_effect.csv -1 125 
java -jar macrophage.jar true 72 results/ph_effect/ 72_ph_effect.csv -1 125 
java -jar macrophage.jar true 73 results/ph_effect/ 73_ph_effect.csv -1 125 
java -jar macrophage.jar true 74 results/ph_effect/ 74_ph_effect.csv -1 125 
java -jar macrophage.jar true 75 results/ph_effect/ 75_ph_effect.csv -1 125 
java -jar macrophage.jar true 76 results/ph_effect/ 76_ph_effect.csv -1 125 
java -jar macrophage.jar true 77 results/ph_effect/ 77_ph_effect.csv -1 125 
java -jar macrophage.jar true 78 results/ph_effect/ 78_ph_effect.csv -1 125 
java -jar macrophage.jar true 79 results/ph_effect/ 79_ph_effect.csv -1 125 
java -jar macrophage.jar true 80 results/ph_effect/ 80_ph_effect.csv -1 125 
java -jar macrophage.jar true 81 results/ph_effect/ 81_ph_effect.csv -1 125 
java -jar macrophage.jar true 82 results/ph_effect/ 82_ph_effect.csv -1 125 
java -jar macrophage.jar true 83 results/ph_effect/ 83_ph_effect.csv -1 125 
java -jar macrophage.jar true 84 results/ph_effect/ 84_ph_effect.csv -1 125 
java -jar macrophage.jar true 85 results/ph_effect/ 85_ph_effect.csv -1 125 
java -jar macrophage.jar true 86 results/ph_effect/ 86_ph_effect.csv -1 125 
java -jar macrophage.jar true 87 results/ph_effect/ 87_ph_effect.csv -1 125 
java -jar macrophage.jar true 88 results/ph_effect/ 88_ph_effect.csv -1 125 
java -jar macrophage.jar true 89 results/ph_effect/ 89_ph_effect.csv -1 125 
java -jar macrophage.jar true 90 results/ph_effect/ 90_ph_effect.csv -1 125 
java -jar macrophage.jar true 91 results/ph_effect/ 91_ph_effect.csv -1 125 
java -jar macrophage.jar true 92 results/ph_effect/ 92_ph_effect.csv -1 125 
java -jar macrophage.jar true 93 results/ph_effect/ 93_ph_effect.csv -1 125 
java -jar macrophage.jar true 94 results/ph_effect/ 94_ph_effect.csv -1 125 
java -jar macrophage.jar true 95 results/ph_effect/ 95_ph_effect.csv -1 125 
java -jar macrophage.jar true 96 results/ph_effect/ 96_ph_effect.csv -1 125 
java -jar macrophage.jar true 97 results/ph_effect/ 97_ph_effect.csv -1 125 
java -jar macrophage.jar true 98 results/ph_effect/ 98_ph_effect.csv -1 125 
java -jar macrophage.jar true 99 results/ph_effect/ 99_ph_effect.csv -1 125 
java -jar macrophage.jar false 0 results/no_ph_effect/ 0_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 1 results/no_ph_effect/ 1_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 2 results/no_ph_effect/ 2_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 3 results/no_ph_effect/ 3_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 4 results/no_ph_effect/ 4_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 5 results/no_ph_effect/ 5_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 6 results/no_ph_effect/ 6_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 7 results/no_ph_effect/ 7_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 8 results/no_ph_effect/ 8_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 9 results/no_ph_effect/ 9_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 10 results/no_ph_effect/ 10_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 11 results/no_ph_effect/ 11_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 12 results/no_ph_effect/ 12_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 13 results/no_ph_effect/ 13_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 14 results/no_ph_effect/ 14_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 15 results/no_ph_effect/ 15_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 16 results/no_ph_effect/ 16_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 17 results/no_ph_effect/ 17_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 18 results/no_ph_effect/ 18_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 19 results/no_ph_effect/ 19_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 20 results/no_ph_effect/ 20_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 21 results/no_ph_effect/ 21_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 22 results/no_ph_effect/ 22_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 23 results/no_ph_effect/ 23_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 24 results/no_ph_effect/ 24_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 25 results/no_ph_effect/ 25_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 26 results/no_ph_effect/ 26_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 27 results/no_ph_effect/ 27_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 28 results/no_ph_effect/ 28_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 29 results/no_ph_effect/ 29_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 30 results/no_ph_effect/ 30_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 31 results/no_ph_effect/ 31_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 32 results/no_ph_effect/ 32_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 33 results/no_ph_effect/ 33_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 34 results/no_ph_effect/ 34_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 35 results/no_ph_effect/ 35_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 36 results/no_ph_effect/ 36_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 37 results/no_ph_effect/ 37_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 38 results/no_ph_effect/ 38_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 39 results/no_ph_effect/ 39_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 40 results/no_ph_effect/ 40_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 41 results/no_ph_effect/ 41_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 42 results/no_ph_effect/ 42_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 43 results/no_ph_effect/ 43_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 44 results/no_ph_effect/ 44_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 45 results/no_ph_effect/ 45_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 46 results/no_ph_effect/ 46_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 47 results/no_ph_effect/ 47_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 48 results/no_ph_effect/ 48_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 49 results/no_ph_effect/ 49_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 50 results/no_ph_effect/ 50_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 51 results/no_ph_effect/ 51_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 52 results/no_ph_effect/ 52_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 53 results/no_ph_effect/ 53_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 54 results/no_ph_effect/ 54_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 55 results/no_ph_effect/ 55_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 56 results/no_ph_effect/ 56_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 57 results/no_ph_effect/ 57_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 58 results/no_ph_effect/ 58_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 59 results/no_ph_effect/ 59_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 60 results/no_ph_effect/ 60_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 61 results/no_ph_effect/ 61_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 62 results/no_ph_effect/ 62_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 63 results/no_ph_effect/ 63_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 64 results/no_ph_effect/ 64_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 65 results/no_ph_effect/ 65_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 66 results/no_ph_effect/ 66_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 67 results/no_ph_effect/ 67_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 68 results/no_ph_effect/ 68_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 69 results/no_ph_effect/ 69_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 70 results/no_ph_effect/ 70_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 71 results/no_ph_effect/ 71_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 72 results/no_ph_effect/ 72_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 73 results/no_ph_effect/ 73_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 74 results/no_ph_effect/ 74_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 75 results/no_ph_effect/ 75_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 76 results/no_ph_effect/ 76_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 77 results/no_ph_effect/ 77_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 78 results/no_ph_effect/ 78_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 79 results/no_ph_effect/ 79_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 80 results/no_ph_effect/ 80_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 81 results/no_ph_effect/ 81_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 82 results/no_ph_effect/ 82_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 83 results/no_ph_effect/ 83_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 84 results/no_ph_effect/ 84_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 85 results/no_ph_effect/ 85_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 86 results/no_ph_effect/ 86_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 87 results/no_ph_effect/ 87_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 88 results/no_ph_effect/ 88_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 89 results/no_ph_effect/ 89_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 90 results/no_ph_effect/ 90_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 91 results/no_ph_effect/ 91_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 92 results/no_ph_effect/ 92_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 93 results/no_ph_effect/ 93_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 94 results/no_ph_effect/ 94_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 95 results/no_ph_effect/ 95_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 96 results/no_ph_effect/ 96_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 97 results/no_ph_effect/ 97_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 98 results/no_ph_effect/ 98_no_ph_effect.csv -1 125 
java -jar macrophage.jar false 99 results/no_ph_effect/ 99_no_ph_effect.csv -1 125 
